### ISSUE TITLE
Retrieval error

### ISSUE THREAD

**Issue by DarrenPIngram** [costis94/bookcut#17]
bookcut, version 1.3.3

Error when retrieving a book. Copy of entire activity.

di@MacPro downloads % bookcut search -t "Theory and Practice of Contrast: Integrating Science, Art and Philosophy" 

 ____              _     ____      _   
| __ )  ___   ___ | | __/ ___|   _| |_ 
|  _ \ / _ \ / _ \| |/ / |  | | | | __|
| |_) | (_) | (_) |   <| |__| |_| | |_ 
|____/ \___/ \___/|_|\_\\____\__,_|\__|
                                       

**********************************
Welcome to BookCut! I'm here to
help you to read your favourite books!
**********************************
Searching for: Theory and practice of contrast: integrating science, art and philosophy
Connected to: http://libgen.li/
           Author(s)  ... Extension
1  Mariusz Stanowski  ...       pdf

[1 rows x 8 columns]

Please enter a number from 1 to 1 to download a book or press "C" to abort search: 1
Connected to: http://libgen.li/
First Link: http://libgen.li//ads.php?md5=a62d7fc594b25398b9ebad673a40ae5c
Traceback (most recent call last):
  File "/usr/local/bin/bookcut", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/bookcut/bookcut.py", line 130, in searching
    details = link_finder(link, mirror_used)
  File "/usr/local/lib/python3.9/site-packages/bookcut/search.py", line 40, in link_finder
    filename = soup.find('input')['value']
TypeError: 'NoneType' object is not subscriptable

**Comment by costis94** [comment]
Hi there. Thank you for your issue report. You actually found a huge bug, which is about the parsing of the file name. 


The issue will be resolved in the next version ASAP.

**Comment by DarrenPIngram** [comment]
Thanks!

**Comment by costis94** [comment]
Issue Resolved.
Please update to BookCut 1.3.6
