### ISSUE TITLE
no form matching name 'libgen'

### ISSUE THREAD

**Issue by dmwyatt** [costis94/bookcut#22]
`$ bookcut book -b "White Fang" -a "Jack London"`

```
Searching for White fang by Jack london
Connected to: http://libgen.li/
Traceback (most recent call last):
  File "c:\users\dustin\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dustin\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\Scripts\bookcut.exe\__main__.py", line 7, in <module>
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\bookcut\bookcut.py", line 98, in book
    libgen_book_find(
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\bookcut\book.py", line 18, in libgen_book_find
    result = book.search()
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\bookcut\book.py", line 69, in search
    br.select_form("libgen")
  File "C:\Users\dustin\.local\pipx\.cache\3b1d662aa11f0ae\lib\site-packages\mechanize\_mechanize.py", line 681, in select_form
    raise FormNotFoundError("no form matching " + description)
mechanize._mechanize.FormNotFoundError: no form matching name 'libgen'
```

Probably some HTML changes at libgen.li...

**Comment by E-11-V** [comment]
Same issue here

**Comment by Aha-Eureka** [comment]
same here on mac
